CREATE TABLE MEDICATIONS(
   MEDID INT PRIMARY KEY NOT NULL,
   GNAME NCHAR(50) NOT NULL,
   BNAME NCHAR(50) NOT NULL,
   COND1 NCHAR(50) NOT NULL,
   COND2 NCHAR(50),
   COND3 NCHAR(50),
   BTFLAG INT
);

INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (1, 'Acyclovir ', 'Zovirax ', 'Herpes', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (2, 'Adalimumab ', 'Humira ', 'Inflammation', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (3, 'Albuterol ', 'ProAir HFA ', 'Asthma', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (4, 'Alendronate ', 'Fosamax ', 'Osteoporosis', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (5, 'Allopurinol ', 'Zyloprim ', 'Gout', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (6, 'Alprazolam ', 'Xanax ', 'Anxiety', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (7, 'Amitriptyline ', 'Elavil ', 'Depression', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (8, 'Amlodipine ', 'Norvasc ', 'HTN/CC Block', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (9, 'Amoxicillin ', 'Amoxil ', 'Antibiotic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (10, 'Amphetamine ', 'Adderall ', 'ADHD', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (11, 'Aripiprazole ', 'Abilify ', 'Antipsychotic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (12, 'Atenolol ', 'Tenormin ', 'HTN/B-Block', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (13, 'Atomoxetine ', 'Strattera ', 'ADHD', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (14, 'Atorvastatin ', 'Lipitor ', 'Cholesterol', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (15, 'Azithromycin ', 'Zithromax ', 'Antibiotic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (16, 'Baclofen ', 'Gablofen ', 'Muscle Relaxer', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (17, 'Benazepril ', 'Lotensin ', 'HTN/ACE Inhib', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (18, 'Benzonatate ', 'Tessalon ', 'Antitussive', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (19, 'Benztropine ', 'Cogentin ', 'Parkinsons', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (20, 'Bisoprolol ', 'Zebeta ', 'HTN/B-Block', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (21, 'Budesonide ', 'Uceris ', 'Ulcerative colitis', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (22, 'Buprenorphine ', 'Suboxone ', 'Addiction', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (23, 'Bupropion ', 'Wellbutrin ', 'Depression', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (24, 'Buspirone ', 'Buspar ', 'Anxiety', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (25, 'Carisoprodol ', 'Soma ', 'Muscle Relaxer', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (26, 'Carvedilol ', 'Coreg ', 'CHF', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (27, 'Cefdinir ', 'Omnicef ', 'Antibiotic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (28, 'Cefuroxime ', 'Ceftin ', 'Antibiotic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (29, 'Celecoxib ', 'Celebrex ', 'NSAID', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (30, 'Cephalexin ', 'Keflex ', 'Antibiotic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (31, 'Cetirizine ', 'Zyrtec ', 'Allergies', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (32, 'Ciprofloxacin ', 'Cipro ', 'Antibiotic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (33, 'Citalopram ', 'Celexa ', 'Depression', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (34, 'Clarithromycin ', 'Biaxin ', 'Antibiotic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (35, 'Clindamycin ', 'Cleocin ', 'Antibiotic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (36, 'Clobetasol ', 'Clovate ', 'Corticosteroid', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (37, 'Clonazepam ', 'Klonopin ', 'Anxiety', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (38, 'Clonidine ', 'Catapres ', 'Hypertension', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (39, 'Clopidogrel ', 'Plavix ', 'Anti-Platelet', null, null, 1);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (40, 'Clotrimazole ', 'Lotrimin ', 'Antifungal', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (41, 'Codeine / APAP ', 'Tylenol #2 ', 'Pain Relief', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (42, 'Colchicine ', 'Colcrys ', 'Gout', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (43, 'Cyclobenzaprine ', 'Flexeril ', 'Muscle Relaxer', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (44, 'Dabigatran ', 'Pradaxa ', 'Anticoagulant', null, null, 1);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (45, 'Desvenlafaxine ', 'Pristiq ', 'Depression', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (46, 'Dexlansoprazole ', 'Dexilant ', 'GERD', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (47, 'Dexmethylphenidate ', 'Focalin ', 'ADHD', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (48, 'Diazepam ', 'Valium ', 'Anxiety', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (49, 'Diclofenac ', 'Voltaren ', 'NSAID', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (50, 'Dicyclomine ', 'Bentyl ', 'IBS', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (51, 'Digoxin ', 'Lanoxin ', 'CHF', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (52, 'Diltiazem ', 'Cardizem ', 'Hypertension', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (53, 'Divalproex ', 'Depakote ', 'Anticonvulsant', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (54, 'Doxazosin ', 'Cardura ', 'Freq. Urination', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (55, 'Doxycycline ', 'Vibramycin ', 'Antibiotic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (56, 'Duloxetine ', 'Cymbalta ', 'Depression', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (57, 'Dutasteride ', 'Avodart ', 'BPH', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (58, 'Enalapril ', 'Vasotec ', 'HTN/ACE Inhib', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (59, 'Enoxaparin ', 'Lovenox ', 'Anticoagulant', null, null, 1);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (60, 'Escitalopram ', 'Lexapro ', 'Depression', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (61, 'Esomeprazole ', 'Nexium ', 'GERD', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (62, 'Estrogen ', 'Premarin ', 'Menopause', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (63, 'Eszopiclone ', 'Lunesta ', 'Sleep Aid', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (64, 'Etanercept ', 'Enbrel ', 'Arthritis', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (65, 'Ezetimibe ', 'Zetia ', 'Cholesterol', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (66, 'Ezetimibe Simvastatin', 'Vytorin ', 'Cholesterol', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (67, 'Famotidine ', 'Pepcid ', 'GERD', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (68, 'Febuxostat ', 'Uloric ', 'Gout', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (69, 'Fentanyl ', 'Duragesic ', 'Pain', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (70, 'Fexofenadine ', 'Allegra ', 'Allergies', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (71, 'Finasteride ', 'Proscar ', 'BPH', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (72, 'Fluconazole ', 'Diflucan ', 'Antifungal', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (73, 'Fluoxetine ', 'Prozac ', 'Depression', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (74, 'Fluticasone ', 'Flonase ', 'Allergies', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (75, 'Folic Acid ', 'Folvite ', 'Supplement', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (76, 'Furosemide ', 'Lasix ', 'Diuretic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (77, 'Gabapentin ', 'Neurontin ', 'Anticonvulsant', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (78, 'Gemfibrozil ', 'Lopid ', 'Cholesterol', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (79, 'Glipizide ', 'Glucotrol ', 'Diabetes', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (80, 'Glyburide ', 'Diabeta ', 'Diabetes', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (81, 'Guiafenesin ', 'Robitussin ', 'Expectorant', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (82, 'Hydralazine ', 'Apresoline ', 'Hypertension', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (83, 'Hydrochlorothiazide ', 'HCTZ ', 'Diuretic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (84, 'Hydrocodone/APAP ', 'Vicodin ', 'Pain Relief', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (85, 'Ibuprofen ', 'Advil ', 'NSAID', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (86, 'Insulin Aspart ', 'Novolog ', 'Diabetes', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (87, 'Insulin Detemir ', 'Levemir ', 'Diabetes', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (88, 'Insulin Glargine ', 'Lantus ', 'Diabetes', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (89, 'Insulin Lispro ', 'Humalog ', 'Diabetes', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (90, 'Irbesartan ', 'Avapro ', 'HTN/A2RB', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (91, 'Ketoconazole ', 'Nizoral ', 'Antifungal', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (92, 'Lamotrigine ', 'Lamictal ', 'Anticonvulsant', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (93, 'Lansoprazole ', 'Prevacid ', 'GERD', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (94, 'Latanoprost ', 'Xalatan ', 'Glaucoma', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (95, 'Levofloxacin ', 'Levaquin ', 'Antibiotic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (96, 'Levothyroxine ', 'Synthroid ', 'Thyroid', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (97, 'Liraglutide ', 'Victoza ', 'Diabetes', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (98, 'Lisdexamfetamine ', 'Vyvanse ', 'ADHD', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (99, 'Lisinopril ', 'Prinivil ', 'HTN/ACE Inhib', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (100, 'Lomitapide ', 'Juxtapid ', 'Cholesterol', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (101, 'Lorazepam ', 'Ativan ', 'Anxiety', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (102, 'Losartan ', 'Cozaar ', 'Hypertension', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (103, 'Lovastatin ', 'Mevacor ', 'Cholesterol', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (104, 'Lurasidone ', 'Latuda ', 'Antipsychotic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (105, 'Meclizine ', 'Dramamine ', 'Antiemetic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (106, 'Meloxicam ', 'Mobic ', 'Arthritis', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (107, 'Memantine ', 'Namenda ', 'Alzheimers', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (108, 'Metformin ', 'Glucophage ', 'Diabetes', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (109, 'Methadone ', 'Dolophine ', 'Addiction', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (110, 'Methocarbamol ', 'Robaxin ', 'Muscle Relaxer', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (111, 'Methotrexate ', 'Rheumatrex ', 'Arthritis', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (112, 'Methylphenidate ', 'Concerta ', 'ADHD', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (113, 'Methylprednisolone ', 'Medrol ', 'Corticosteroid', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (114, 'Metoclopramide ', 'Reglan ', 'GERD', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (115, 'Metoprolol ', 'Lopressor ', 'HTN/B-Block', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (116, 'Metronidazole ', 'Flagyl ', 'Antibiotic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (117, 'Minocycline ', 'Minocin ', 'Antibiotic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (118, 'Mirtazepine ', 'Remeron ', 'Depression', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (119, 'Mometasone ', 'Nasonex ', 'Allergies', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (120, 'Montelukast ', 'Singulair ', 'Asthma', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (121, 'Moxifloxacin ', 'Avelox ', 'Antibacterial', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (122, 'Mupirocin ', 'Bactroban ', 'Antibacterial', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (123, 'Nabumetone ', 'Relafen ', 'NSAID', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (124, 'Naproxen ', 'Aleve ', 'NSAID', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (125, 'Nebivolol ', 'Bystolic ', 'HTN/B-Block', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (126, 'Niacin ', 'Niaspan ', 'Cholesterol', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (127, 'Nifedipine ', 'Procardia ', 'HTN/CC Block', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (128, 'Nitrofurantoin ', 'Macrobid ', 'Antibiotic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (129, 'Nitroglycerine ', 'NitroStat SL ', 'Angina', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (130, 'Nortriptyline ', 'Pamelor ', 'Depression', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (131, 'Olanzapine ', 'Zyprexa ', 'Antipsychotic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (132, 'Olmesartan ', 'Benicar ', 'HTN/A2RB', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (133, 'Olopatadine ', 'Patanol ', 'Antihistamine', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (134, 'Omeprazole ', 'Prilosec ', 'GERD', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (135, 'Ondansetron ', 'Zofran ', 'Antiemetic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (136, 'Oseltamivir ', 'Tamiflu ', 'Antiviral (Flu)', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (137, 'Oxybutynin ', 'Ditropan ', 'Incontinence', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (138, 'Oxycodone ', 'OxyContin ', 'Pain Relief', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (139, 'Oxycodone/APAP ', 'Percocet ', 'Pain Relief', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (140, 'Pantoprazole ', 'Protonix ', 'GERD', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (141, 'Paroxetine ', 'Paxil ', 'Depression', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (142, 'Penicillin ', 'Pen VK ', 'Antibiotic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (143, 'Phenazopyridine ', 'Pyridium ', 'UTI', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (144, 'Phentermine ', 'Adipex P ', 'Weight Loss', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (145, 'Phenytoin ', 'Dilantin ', 'Anticonvulsant', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (146, 'Pioglitazone ', 'Actos ', 'Diabetes', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (147, 'Potassium ', 'K-Tab ', 'Electrolyte', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (148, 'Pramipexole ', 'Mirapex ', 'Parkinsons', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (149, 'Pravastatin ', 'Pravachol ', 'Cholesterol', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (150, 'Prednisone ', 'Deltasone ', 'Inflammation', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (151, 'Pregabalin ', 'Lyrica ', 'Anticonvulsant', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (152, 'Promethazine ', 'Phenergan ', 'Antihistamine', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (153, 'Propranolol ', 'Inderal ', 'Hypertension', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (154, 'Quetiapine ', 'Seroquel ', 'Antipsychotic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (155, 'Quinapril ', 'Accupril ', 'HTN/ACE Inhib', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (156, 'Rabeprazole ', 'Aciphex ', 'GERD', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (157, 'Raloxifene ', 'Evista ', 'Osteoporosis', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (158, 'Ramipril ', 'Altace ', 'Hypertension', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (159, 'Ranitidine ', 'Zantac ', 'GERD', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (160, 'Risedronate ', 'Actonel ', 'Osteoporosis', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (161, 'Risperidone ', 'Risperdal ', 'Antipsychotic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (162, 'Rivaroxaban ', 'Xarelto ', 'Blood Thinner', null, null, 1);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (163, 'Rivastigmine ', 'Exelon ', 'Dementia', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (164, 'Roflumilast ', 'Daliresp ', 'COPD', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (165, 'Ropinirole ', 'Requip ', 'Parkinsons', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (166, 'Rosuvastatin ', 'Crestor ', 'Cholesterol', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (167, 'Saxagliptin ', 'Onglyza ', 'Diabetes', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (168, 'Sertraline ', 'Zoloft ', 'Depression', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (169, 'Sildenafil ', 'Viagra ', 'Impotence', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (170, 'Simvastatin ', 'Zocor ', 'Cholesterol', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (171, 'Sitagliptin ', 'Januvia ', 'Diabetes', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (172, 'Solifenacin ', 'VESIcare ', 'Overactive Bladder', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (173, 'Spironolactone ', 'Aldactone ', 'Diuretic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (174, 'Sumatriptan ', 'Imitrex ', 'Migraine', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (175, 'Tadalifil ', 'Cialis ', 'Impotence', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (176, 'Tamsulosin ', 'Flomax ', 'Freq. Urination', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (177, 'Temazepam ', 'Restoril ', 'Sleep Aid', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (178, 'Terazosin ', 'Hytrin ', 'BPH', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (179, 'Testosterone ', 'AndroGel ', 'Low T', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (180, 'Thyroid ', 'Armour Thyroid', 'Thyroid', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (181, 'Ticagrelor ', 'Brilinta ', 'Anti-Platelet', null, null, 1);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (182, 'Tiotropium ', 'Spiriva ', 'COPD', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (183, 'Tizanidine ', 'Zanaflex ', 'Muscle Relaxer', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (184, 'Tolterodine ', 'Detrol ', 'Incontinence', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (185, 'Topiramate ', 'Topamax ', 'Anticonvulsant', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (186, 'Tramadol ', 'Ultram ', 'Pain Relief', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (187, 'Travoprost ', 'Travatan ', 'Glaucoma/HTN', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (188, 'Trazodone ', 'Desyrel ', 'Depression', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (189, 'Triamcinolone ', 'Kenalog ', 'Corticosteroid', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (190, 'Triamterene/HCTZ ', 'Dyazide ', 'Diuretic', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (191, 'Valacyclovir ', 'Valtrex ', 'Herpes', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (192, 'Valsartan ', 'Diovan ', 'HTN/A2RB', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (193, 'Vardenafil ', 'Levitra ', 'Impotence', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (194, 'Varenicline ', 'Chantix ', 'Smoking', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (195, 'Venlafaxine ', 'Effexor ', 'Depression', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (196, 'Verapamil ', 'Verelan ', 'HTN/CC Block', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (197, 'Vitamin D ', 'Caltrate ', 'Supplement', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (198, 'Warfarin ', 'Coumadin ', 'Blood Thinner', null, null, 1);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (199, 'Zolpidem ', 'Ambien ', 'Insomnia', null, null, 0);
INSERT INTO Medications (MEDID, GNAME, BNAME, COND1, COND2, COND3, BTFLAG) VALUES (200, 'Zoster Vaccine ', 'Zostavax ', 'Shingles', null, null, 0);


